// Generated by https://quicktype.io

export interface InitialState {
  peoples: People[];
  peopleView: People;
  loading: boolean;
  error: Error;
}
export interface People {
  id?: number;
  name: string;
  email: string;
  gender: string;
  status: string;
}
export interface Error {
  error: boolean;
  message: string;
}
export interface DataTypeColumns {
  key: string;
  person: string;
  actions: string[];
}
